sudo: required
addons:
  - chrome: stable

env:
  global:
    DISPLAY: ":99.0"

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.1-without-puma.gemfile
before_install:
  - google-chrome-stable --version
  - gem update bundler
notifications:
  webhooks:
    - https://webhook.commit-email.info/
